import React from 'react';
import { Text } from 'react-native';

export default function LoremIpsumText() {
    return (
        <Text>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi in ultrices orci, quis gravida tortor. Vivamus feugiat malesuada risus, eu fringilla elit convallis quis. In placerat nec dolor sit amet semper. Cras sed ultrices est. Donec blandit, mauris suscipit sodales semper, mi leo tristique nisi, a pharetra nibh risus at lacus. Praesent sit amet elementum diam. Donec risus mauris, efficitur vitae sapien nec, blandit pellentesque est. Mauris ipsum diam, tristique at nisi nec, convallis mattis arcu. Sed eget pretium odio. Quisque vehicula nibh sed quam vulputate, sed iaculis eros molestie. Proin in erat non quam finibus scelerisque. Sed ut velit sed magna luctus congue sed in nibh.

            Quisque laoreet mollis vestibulum. Vestibulum a lobortis orci. Aliquam ac auctor ante, vitae finibus dui. Nunc mollis, mauris id vehicula feugiat, risus odio hendrerit nisi, sit amet luctus dui lorem at lacus. Etiam faucibus et nisi ut tempus. Duis massa tellus, tempus non placerat sed, varius vel nulla. Phasellus eu enim in magna vehicula mattis. Etiam non urna sit amet leo aliquet ullamcorper. Aenean ornare neque sed ipsum porttitor pellentesque. Praesent non magna sit amet mauris lacinia consequat vitae et felis. Praesent pulvinar diam vel risus dignissim, eget iaculis dolor volutpat. Vestibulum non semper felis.

            Sed ut luctus eros. Morbi sit amet enim in metus convallis convallis. Proin condimentum malesuada aliquam. Maecenas mattis metus elit, a semper purus lacinia sit amet. Vivamus lobortis faucibus ultricies. Pellentesque mi sapien, vestibulum nec dapibus in, ultrices in nisi. Nam cursus ipsum at orci molestie, id elementum ipsum fringilla. Nulla nec vehicula nisl, sed placerat lacus. Nam pretium tortor justo, et tristique odio tincidunt sit amet.

            Donec hendrerit auctor ipsum, id efficitur turpis fermentum sed. Pellentesque dui mi, faucibus sed interdum viverra, viverra sit amet nunc. Praesent venenatis justo eu dolor aliquet porttitor. Maecenas aliquam, arcu sit amet fermentum efficitur, arcu ligula auctor dolor, nec ornare eros elit aliquet urna. Cras finibus eget nibh eget consequat. Sed non magna eu risus semper facilisis. Nulla imperdiet sit amet sem id sagittis. Ut laoreet dolor at ornare dignissim. Integer feugiat dolor vel interdum eleifend. Quisque porttitor ornare nisl, non molestie dolor scelerisque sit amet. Morbi accumsan, tortor vitae gravida consequat, enim justo gravida sem, porttitor dictum justo justo et mi.

            Nulla suscipit diam eget risus lobortis hendrerit. Donec mollis aliquam ligula, nec consectetur dolor bibendum ac. Aenean in erat in eros tempus luctus. Praesent nec urna id augue lacinia rutrum id quis eros. Cras non libero egestas, sodales velit eu, ornare nibh. Ut lacinia leo ut tempor sollicitudin. Nam semper condimentum erat, sit amet porta dolor dignissim eget. Curabitur tincidunt dictum diam eu suscipit. Morbi turpis ex, eleifend nec efficitur vel, laoreet at ligula. Nunc iaculis, arcu non vehicula pretium, tellus est semper lorem, finibus volutpat leo mauris posuere purus. Maecenas quis lorem quis magna porta semper. Mauris aliquet leo euismod tellus interdum eleifend. Nullam ac convallis sem. Donec rhoncus, dui ac tristique gravida, elit mauris malesuada lectus, at sodales leo eros vel mauris.

            Sed non eros ante. Sed vitae maximus mi. Sed tempus nec ipsum ut cursus. Mauris et laoreet tortor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut eleifend ipsum nec risus iaculis, ut posuere ex fermentum. Pellentesque euismod efficitur felis molestie porttitor. Vivamus sit amet velit est. Sed dapibus, ipsum nec venenatis convallis, elit felis dapibus ipsum, eget scelerisque nunc ex ac justo. Suspendisse ac rhoncus tortor. Mauris eros ligula, posuere non hendrerit quis, tempus sed odio. Duis quis est vitae metus vehicula vehicula. Aliquam pharetra augue quis justo varius, ac fringilla est lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec pellentesque orci. Sed fringilla tristique fringilla.

            Mauris varius dapibus suscipit. Donec eget libero sed augue finibus tristique. Nullam interdum, ante condimentum suscipit semper, leo neque porta orci, in varius sem massa id neque. Nulla at tortor ac justo scelerisque sollicitudin non in massa. Mauris eu arcu urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ullamcorper nulla libero, ut tempor nunc sollicitudin sit amet. In hac habitasse platea dictumst. Cras et scelerisque ante. Nunc eu accumsan nisl, id pellentesque nulla. Nunc et nunc ut nisl venenatis euismod id in metus. Ut vitae rhoncus arcu. Donec viverra scelerisque libero, ut aliquam est tincidunt id. Vestibulum in diam congue, suscipit metus id, rhoncus velit. Quisque eget molestie elit, id vulputate purus.

            Sed tempus libero quis blandit aliquet. Sed non orci et tellus luctus feugiat gravida et eros. Ut id turpis vel turpis pulvinar pulvinar a nec elit. Nullam vehicula eleifend vulputate. Morbi tincidunt arcu ac dolor euismod lacinia. Curabitur placerat, nisl eget tincidunt cursus, massa augue commodo ante, a luctus ligula magna id lectus. Integer ultrices, tellus sit amet dictum pharetra, orci justo maximus ipsum, a cursus sapien lorem non ligula. Fusce faucibus neque magna, eget consequat justo viverra vitae. Vivamus in tempor leo. Quisque id eleifend ipsum. Maecenas in pellentesque risus. Donec faucibus vestibulum ipsum, varius tincidunt turpis malesuada nec.

            Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis vehicula nunc vel dui varius fringilla id in elit. Integer ut quam posuere, consectetur sapien sodales, aliquet ex. In dapibus tincidunt interdum. Suspendisse posuere eleifend justo, sit amet egestas nunc pellentesque eget. Nunc commodo dictum risus, eu dapibus lacus luctus in. Vestibulum sollicitudin est ante, ut lacinia velit tincidunt ut. Mauris id ligula sapien. Donec justo ante, elementum at ultricies at, bibendum nec tellus. Phasellus elementum felis at massa vehicula scelerisque. Cras gravida aliquam risus, eu ultricies ligula congue ultrices. Aenean volutpat, nisl sit amet tincidunt convallis, purus ipsum blandit mi, a ultrices nunc mi at eros. Nulla dapibus massa ut enim tincidunt, sed efficitur nulla pulvinar.

            Vivamus iaculis neque quis nibh varius egestas. Suspendisse mattis nunc non sagittis fringilla. Pellentesque id odio finibus, interdum tellus vitae, ornare ligula. Nam nec urna vestibulum, euismod eros et, consectetur purus. Aenean consectetur tellus vitae lectus commodo, eget dictum velit pharetra. Vestibulum porta vel felis eget iaculis. Nunc quis faucibus eros. Vivamus tempus mattis arcu eu maximus. Proin pellentesque odio quis pulvinar pellentesque. Nunc quis orci ut diam egestas ultrices. Suspendisse bibendum ac felis iaculis consectetur. Etiam magna arcu, laoreet id mauris id, semper vestibulum metus. Quisque rhoncus rhoncus scelerisque. Cras lobortis dui vitae luctus varius. Pellentesque ultrices fermentum turpis, eu scelerisque leo ornare at.

            Integer sed pulvinar purus, in efficitur purus. Nulla eu pharetra mauris. Vivamus aliquam dolor tellus. Praesent mauris urna, hendrerit ut convallis sit amet, dapibus ut magna. Vivamus nunc lacus, gravida vitae luctus et, venenatis vel magna. Nulla fermentum nisi nec justo auctor, quis vulputate sem luctus. Vestibulum ultrices justo eu ultricies sagittis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque blandit sapien feugiat lacus hendrerit, non tincidunt neque cursus. Etiam consectetur feugiat augue.

            Sed sed nisl turpis. Proin vel placerat odio, a lobortis diam. Proin condimentum porttitor erat, a auctor neque pretium vitae. Sed tristique cursus lacus, ac fringilla lectus placerat id. Praesent tempus auctor tortor, vitae mollis mauris. Morbi malesuada est neque, quis iaculis nibh pharetra ut. Aenean tincidunt elit vitae nisl mattis, vitae convallis mauris condimentum. Mauris non nisi libero. Praesent faucibus odio vitae mauris euismod fringilla.

            Ut consequat justo quam, nec malesuada justo condimentum nec. Nam maximus velit odio, eu lobortis mi aliquam ultricies. Mauris molestie enim sit amet elit placerat, a porta arcu feugiat. Nunc sed purus consequat, consequat quam in, dapibus lectus. Nullam tortor metus, sodales quis hendrerit sed, sagittis non tortor. Vestibulum varius ipsum eget congue volutpat. Integer ultricies felis vel tortor venenatis mollis. Aenean eget varius ex, vitae ornare ligula.

            Sed semper urna augue, vel rutrum velit finibus sit amet. Vestibulum congue massa vel sem venenatis volutpat. Aliquam pellentesque rhoncus leo sed finibus. Nulla et libero vel ligula commodo imperdiet ac sit amet sapien. Quisque ultricies massa id varius consectetur. Curabitur turpis felis, porta ac mi et, blandit tincidunt erat. Donec blandit lacus et velit commodo, ut fermentum orci fringilla. Donec enim justo, sodales eu elementum pharetra, elementum ac risus. Sed tempor ante vel tristique convallis. Suspendisse nisi purus, tristique id ultricies eget, consectetur at metus. Proin sit amet rhoncus orci, a suscipit justo. Integer ligula felis, efficitur sit amet venenatis a, consequat at tortor.

            Nulla mauris massa, rhoncus nec ante nec, tincidunt laoreet purus. Nulla commodo enim a nibh efficitur sagittis in vel sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at tellus eu metus sagittis commodo a ac elit. Pellentesque viverra sapien pretium ante scelerisque gravida. Integer quis libero suscipit, rutrum sapien vitae, porttitor orci. Morbi ut dolor non nisl blandit pellentesque auctor id massa. Ut luctus velit enim, vitae varius diam consequat at. Etiam at condimentum tellus, ut fermentum erat.

            Maecenas malesuada odio sed metus ornare, nec ultricies massa eleifend. Suspendisse potenti. Pellentesque vitae dui at orci tincidunt ornare. Fusce dictum est risus. Sed non elementum odio, non commodo odio. Suspendisse commodo arcu non augue blandit congue. Vestibulum fermentum odio ut velit pellentesque pellentesque. Quisque dignissim vulputate vestibulum. Nam pretium quam eu lacus suscipit tristique. Duis at justo non diam placerat blandit in eget urna. Curabitur efficitur mauris diam, quis vehicula velit efficitur euismod. Etiam a fringilla erat. Donec ullamcorper lorem dignissim ante fermentum ultricies.

            Sed a erat neque. Nulla facilisi. Fusce pulvinar interdum hendrerit. Morbi orci ante, venenatis vel scelerisque vitae, vulputate ut sem. Aenean sit amet malesuada sem, sit amet ultricies tellus. Nam viverra facilisis velit, sit amet fermentum ipsum aliquam vitae. Aliquam finibus sem purus, non tincidunt lectus sodales sodales. Sed placerat, ex eget semper congue, purus nisl suscipit enim, at dapibus ligula ipsum in elit. Nunc condimentum neque ornare nisi rhoncus pulvinar. Aenean blandit ornare magna, dignissim suscipit erat aliquam at.

            Suspendisse a tempor risus, at gravida felis. Mauris nec dui id arcu pretium varius vel non ante. Maecenas nec velit in sem molestie vulputate sit amet et magna. In finibus sapien justo, aliquet ullamcorper justo dapibus eu. Morbi congue hendrerit enim vel eleifend. Quisque vulputate eros nunc, quis semper purus varius sit amet. Nulla tempus risus sed sagittis aliquet.

            Duis vitae mauris ac arcu faucibus aliquam in sit amet odio. Duis tristique pulvinar aliquet. Pellentesque id sagittis lorem. Maecenas nibh est, fermentum a bibendum vitae, cursus in neque. Mauris finibus accumsan risus, ut rhoncus metus ultricies id. Nullam ut nisi sapien. Aenean semper dolor quis erat cursus ullamcorper. Aenean gravida, lectus ut mattis dignissim, felis magna bibendum metus, eu finibus sem mi a diam. Sed a lacus iaculis, aliquet elit in, varius mi. Integer egestas lobortis enim, nec malesuada nulla luctus efficitur.

            Duis ac orci vel massa tempor ornare ut quis erat. Vestibulum vel felis vel justo tincidunt suscipit. Aliquam luctus nunc quis tortor viverra tempor. Proin leo tortor, egestas id purus sit amet, iaculis sagittis lorem. Pellentesque pulvinar diam id ligula consequat malesuada. Phasellus dignissim viverra enim, vitae lobortis turpis tincidunt non. Nulla lacus velit, blandit at lobortis vel, iaculis vitae velit. Etiam vulputate erat vel aliquam elementum. Cras maximus dictum mi, nec elementum enim ultrices eu. Phasellus blandit lorem vitae enim pretium, eget posuere tellus consectetur. Sed accumsan, diam a luctus lobortis, mi elit sollicitudin velit, quis bibendum leo sem sed purus.
        </Text>
    );
}